baseURL = 'http://pedroguillaumon.github.io/'
languageCode = 'en-us'
defaultContentLanguage = "en"
title = 'P.V.Guillaumon'
theme = "spectral-master"
publishDir = "docs"



[params]
fancyTitle = "Dr. Pedro V. Guillaumon" # title for frontpage, may include image
copyright = "P.V.Guillaumon"
description = 'Postdoctoral Researcher at Laboratori Nazionali del Gran Sasso (LNGS-INFN)'
startbuttonText = "Research"
startbuttonLink = "/research/research"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/research/research'
title = "Research"

[[params.menu.main]]
url = '/'
title = "CV"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[[params.menu.main]]
url = '/contact/contact'
title = "Contact"


[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Postdoctoral Researcher at Laboratori Nazionali del Gran Sasso (LNGS-INFN)'
body = '''
I am working with neutrinoless double beta decay and dark matter in CUORE/CUPID/CRESST experiments.
'''



[[params.one.icon]]
icon = "fa-heart-o"
style = "2"
label = "Ipsum"



[params.two]
enable = true

[[params.two.section]]
img = "img/pic01.jpg"
title = 'Nuclear and Particle Astrophysicist'
body = 'I am interested in understanding the fundamentals of our Universe. Some of those questions I got involved are related to the mass of the neutrino and the nature of dark matter. Also, about the origin of the heavy elements in the Universe.'

[[params.two.section]]
img = "img/pic03.jpg"
title = 'Medical Physics'
body = 'I also collaborated with medical physics, specially with developments of new isotopes to threat cancer. As a physicist it is important to help the development of our societ in more direct ways.'

[params.three]
enable = true
title = 'More info'
body = '''
In the Menu tab you can find more information about my research, cv, contact and general posts about interesting subjcts.
'''

[[params.three.feature]]
icon = "fa-paper-plane-o"
title = "E-mail"
body = "pedro . guillaumon AT lngs . infn . it"


[params.cta]
enable = true
title = ""
body = ""

[[params.cta.link]]
href = "#"
text = "Go Up"
special = true

[params.contact]
enable = false
title = "Contact"
body = "Leave us a message."
phone = "+49 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "nospam@example.com"
subject = "New Submission!"
plain = false

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
